add workout actions; refactored
artsich/gachigym pull request #30
Opened 2024-08-27 18:36 UTC by Artemeow

2024-08-27 20:03 UTC, artsich requested changes

2024-08-27 20:03 UTC, artsich commented on src/components/history/workout.jsx
верни тайп скрипт

2024-08-27 20:03 UTC, artsich commented on src/pages/history-page.jsx
идея в том чтобы рендерить и обрабатывать бизнес логику в одном месте скатится в говно...

2024-08-27 20:03 UTC, artsich commented on src/components/history/workout-actions.jsx
> +		setIsProgram(getProgramByName(workout.name) !== undefined);
т.е на каждое открытие лезть в базу и чекать есть ли такая программа?

2024-08-27 20:03 UTC, artsich commented on src/components/history/workout-actions.jsx
> +				isProgram ? onDeleteProgram() : onSaveProgram();
почему разный подход к сохранению программ, на workout-page юзера спрашивают нужно ли заменить

2024-08-27 20:03 UTC, artsich commented on src/components/history/workout-actions.jsx
> +				<Popover.Menu
сделай ребейз и заюзай новый компонент ThemedPopoverMenu, каждый раз лезть в хук за темой слишком запарно

2024-08-27 20:03 UTC, artsich commented on src/components/history/workout.jsx
> +const truncateName = (s, w) => (s.length > w ? s.substring(0, w) + "..." : s);
и как понять названия аргументов, str, len - мб? 

или же заюзать тайпскрипт.

```ts
const truncateName = (str: string, maxLen: number) => ....
```

2024-08-27 20:03 UTC, artsich commented on src/components/history/workout-actions.jsx
> +		setIsProgram(getProgramByName(workout.name) !== undefined);
почему бы просто не сделать препроцессинг workout и добавить ему такое поле?

2024-08-28 10:25 UTC, Artemeow commented on src/pages/history-page.jsx
пока не скатилась оставим так

2024-08-28 10:36 UTC, Artemeow commented on src/components/history/workout-actions.jsx
> +		setIsProgram(getProgramByName(workout.name) !== undefined);
каждый раз, когда юзер жмёт на три точки (открытие меню) - происходит поиск программы. это достаточно плёвая операция

2024-08-28 10:46 UTC, Artemeow commented on src/components/history/workout-actions.jsx
> +				<Popover.Menu
окей

2024-08-28 11:04 UTC, Artemeow commented on src/components/history/workout.jsx
> +const truncateName = (s, w) => (s.length > w ? s.substring(0, w) + "..." : s);
исправил наименования, под тс не переделывал

2024-08-28 14:10 UTC, Artemeow commented on src/components/history/workout-actions.jsx
> +				isProgram ? onDeleteProgram() : onSaveProgram();
исправлю

2024-08-28 14:11 UTC, closed without merging